.PHONY: clean
# clean is a phony target as it is just the name of a recipe, not any file. Making it a phony target ensures clean is always executed, even if there is
# a file of the same name in the directory.
clean: 
	rm *.npy
